[build]
  functions = "netlify/functions"
  command = "pip install -r requirements.txt && cp wsgi_handler.py netlify/functions/hello.py"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/hello"
  status = 200
