[build]
  command = "pip install -r requirements.txt"
  functions = "nfunctions"

[build.environment]
  PYTHON_VERSION = "3.11"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200

[functions]
  directory = "functions"
  node_bundler = "esbuild"